# Generated by Django 3.1 on 2022-02-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeChild1',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.node')),
            ],
            options={
                'verbose_name': 'Нода дерева child 1',
                'verbose_name_plural': 'Ноды дерева child 1',
                'ordering': ('created_at', 'title'),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.node',),
        ),
        migrations.CreateModel(
            name='NodeChild2',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.node')),
            ],
            options={
                'verbose_name': 'Нода дерева child 2',
                'verbose_name_plural': 'Ноды дерева child 2',
                'ordering': ('created_at', 'title'),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.node',),
        ),
    ]
